name: flutter_news
description: A new Flutter application.
version: 1.5.1+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.6
  share: ^2.0.4
  http: ^0.13.3
  cubes: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "imgs/icone.png"

flutter:

  uses-material-design: true
  assets:
      - assets/place_holder.jpg
      - assets/place_holder_2.jpg
      - assets/place_holder_3.jpg
      - resources/lang/en.json
      - resources/lang/pt.json
